# Generated by Django 4.2 on 2024-12-13 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='thumb_nail',
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.URLField(default='http'),
            preserve_default=False,
        ),
    ]
