# Generated by Django 4.2 on 2024-12-14 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_video_video_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='cover_photo',
        ),
    ]
