# Generated by Django 4.2 on 2024-12-15 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_playlist_cover_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='view_count',
        ),
    ]
