# Generated by Django 4.2 on 2025-01-18 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_video_view_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Labels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('videos', models.ManyToManyField(related_name='labels', to='main.video')),
            ],
        ),
    ]
